config/routes.rb
Rails.application.routes.draw do
  devise_for :podcasts
  root 'welcome#index'

end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  def configure_permitted_parameters
    # devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :title)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :title, :description, :itunes, :stitcher, :podbay)}
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Podcastfm</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <!-- Latest compiled and minified CSS -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->

    <!-- Optional theme -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

    <!-- Latest compiled and minified JavaScript -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> -->
  </head>

  <body>
    <% if notice %>
    <p class="notice">
      <%= notice %>
    </p>
    <% elsif alert %>
    <p class="alert">
      <%= alert %></p>
      <% end %>
    <header id="main_header" class="cf">
      <div class="wrapper_wide">
        <%= link_to "Podcast.fm", root_path, id:"logo" %>
        <nav>
          <ul>
            <%unless podcast_signed_in? %>
              <li><a href="#">Explore</a></li>
              <li><%=link_to "Sign In", new_podcast_session_path%></li>
              <li><%=link_to "Create a Podcast", new_podcast_registration_path %></li>
            <% else %>
             <li><a href="#">Dashboard</a></li>
             <li><a href="#">Explore</a></li>
             <li><%=link_to "Sign Out", destroy_podcast_session_path, method: :delete%></li>
           <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div id="background">
   <header class= "cf">
     <div class="wrapper_wide">
       <%= link_to "Podcast.fm", root_path, id:"logo" %>
       <nav>
         <ul>
           <%unless podcast_signed_in? %>
             <li><a href="#">Explore</a></li>
             <li><%=link_to "Sign In", new_podcast_session_path%></li>
             <li><%=link_to "Create a Podcast", new_podcast_registration_path %></li>
           <% else %>
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Explore</a></li>
            <li><%=link_to "Sign Out", destroy_podcast_session_path, method: :delete%></li>
          <% end %>
         </ul>
       </nav>
     </div>
   </header>
   <div class="wrapper_skinny">
     <h1>Discover your new favorite<br> podcast, or create your own.</h1>
     <%=link_to "Create a Podcast", new_podcast_registration_path, class: "button button_highlight" %>
     <%=link_to "Explore", new_podcast_registration_path, class: "button button_white" %>
   </div>
</div>